# Generated by Django 5.2 on 2025-10-27 20:27

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(
            """
            CREATE INDEX description_trgm_idx ON products_product USING GIN (description gin_trgm_ops);
            """,
            "DROP INDEX description_trgm_idx;"
        ),
    ]
